name: features_hooks
description: Hook dependencies for features brick
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mason: ^0.1.0-dev.56
  path: ^1.8.3
  recase: ^4.1.0
